### ISSUE TITLE
Support for multiple database servers

### ISSUE THREAD

**Issue by amsjunior** [influitive/apartment#240] opened 2015-06-17 21:10 UTC
Hi, 

does Apartment support databases/tenants spread across multiple database servers? E.g. if I want to scale out to more DB servers, can I move the databases and somehow tell Apartment which server hosts which DB?

Thanks,
     Antonio.

**Comment by bradrobertson** [comment] 2015-06-18 13:29
Not at the moment. We're actively exploring sharding solutions, but I *think* we'd lean towards a postgres specific solution so that app itself doesn't need to know how to route queries.

It'd be nice if something like [pg_shard](https://github.com/citusdata/pg_shard) supported sharding by schemas.

**Comment by amsjunior** [comment] 2015-06-18 16:06
Thanks for the information Brad. Shall I close this issue?

**Comment by bradrobertson** [comment] 2015-06-19 12:03
Ya I'll close it. We'll definitely keep the community up to date with any information on how to split things up into physical servers as it's a popular question.

**Closed by bradrobertson** 2015-06-19 12:03 UTC

**Comment by mykoweb** [comment] 2016-04-07 20:05
@bradrobertson What is the current status of this?

In your current README, it says there is support for tenants on multiple servers:

https://github.com/influitive/apartment#user-content-tenants-on-different-servers

However, after I add the ```config.tenant_names``` in the ```config/initializers/apartment.rb``` file, and then create the tenant, the new schema and tenant appear in the default db, not the new db defined in the initializer. Am I doing anything wrong:

Here is a snippet from the initializer:

```
Apartment.configure do |config|
  // some lines skipped
  config.tenant_names = {
    'some_tenant' => {
      adapter: 'postgresql',
      host: 'localhost',
      port: 5431,
      encoding: 'utf8',
      database: 'mydb'
    }
  }
```

I'm running locally with 2 postgres instances running, one on port 5432 and one on 5431.

Thanks!

**Comment by bradrobertson** [comment] 2016-04-08 12:52
Hmm... This part I didn't personally write. @apneadiving can you comment? My understanding is the tenant would need to exist to switch to it, but I don't know what this looks like for creating tenants in different locations.

**Comment by apneadiving** [comment] 2016-04-08 13:08
@mykoweb I'm not sure what ou are doing because you mention both schema and database.
Did you set `use_schemas` ?

**Comment by mykoweb** [comment] 2016-04-08 13:38
@apneadiving I'm trying to use the apartment gem where some tenants/schemas are stored on different dB servers, exactly as the original poster described.

**Comment by apneadiving** [comment] 2016-04-08 13:40
@mykoweb currently you cant have both different schemas + different dbs at the same time. Hence my question :)

**Comment by mykoweb** [comment] 2016-04-08 13:43
No, I did not use use_schemas.

I didn't think we could use different schemas on different dbs.  I only asked because your README says otherwise.

**Comment by apneadiving** [comment] 2016-04-08 13:46
I'm curious to know where the doc states both are possible at the same time, please quote so it can be corrected.
Please provide your whole config so I can try on my side

**Comment by mykoweb** [comment] 2016-04-08 13:47
That previous comment should've read different tenants on different dbs, which from the perspective of your gem is really the same thing,  if my understanding is correct.

**Comment by mykoweb** [comment] 2016-04-08 13:49
https://github.com/influitive/apartment#user-content-tenants-on-different-servers

**Comment by mykoweb** [comment] 2016-04-08 13:51
I'm not at my computer right now, but I'll post as soon as I get into the office.

**Comment by mykoweb** [comment] 2016-04-08 14:23
I basically set up my config exactly as the README stated for multiple database server setup:

```
require 'apartment/elevators/subdomain'

Apartment.configure do |config|
  config.tenant_names = {
    'tenant_name' => {
      adapter: 'postgresql',
      host: 'hostname-for-my-other-db-server',
      port: 5432,
      encoding: 'utf8',
      database: 'db-name'
    }
  }
end

Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain'
```

**Comment by mykoweb** [comment] 2016-04-08 14:26
As I stated before, all of this works if I a manually add in the ```ActiveRecord::Base.establish_connection``` before creating or switching tenants that are located on different db servers, but I thought the whole point of this feature was to automatically take care of this.

**Comment by arpitvaishnav** [comment] 2017-05-12 14:04
Is it working now ? I am facing similar issue . I am trying to connect with the different servers and set same configuration as mentioned. I have all the tanent on different servers . Will that be usefull for me now.?

**Comment by mikecmpbll** [comment] 2017-05-12 14:55
@arpitvaishnav it's merged but it's experimental :) feel free to give it a spin and let us know your results ... https://github.com/influitive/apartment#tenants-on-different-servers

you also need to set `config.with_multi_server_setup = true` in your config.

**Comment by arpitvaishnav** [comment] 2017-05-15 10:47
I have tried with the configuration `config.with_multi_server_setup = true`, Its not working properly.
The problem is once I get connect with other server, It does not come back the original server as it tried to find the same tenant in connected server and not the one which should be connected.

I have observed  that  `use database`  requires connection when it tried to connect back to original database which was initialized while servers start. The circle of connecting back is not finishing.

**Comment by mikecmpbll** [comment] 2017-05-16 08:58
@amsjunior how are you trying to switch tenant?

**Comment by amsjunior** [comment] 2017-05-19 04:20
@mikecmpbll, I ended up scaling my database vertically, and consequently did not need to switch between tenants across servers.

**Comment by Ali-raza-khan** [comment] 2024-08-23 12:17
@arpitvaishnav Is this worked for you? I am stuck in kind of same issue where i want to switch the to remote DB on the basis of tenant. If yes then kindly can u share how its working for u?

Thanks
