### ISSUE TITLE
Tenant creation broken with Rails 5 / apartment 1.2 / mysql

### ISSUE THREAD

**Issue by Xorelock** [influitive/apartment#345] opened 2016-07-28 19:29 UTC
Hi, i am so happy to see that you've released 1.2 with support for rails 5. I'm trying to get it up and running, but there are some issues:
1) force cascade on tables in schema.rb cause a failed drop table (why is it trying to drop tables?)
(i temporarily mitigated by removing force cascade from schema.rb)
2) schema_migration tables doesn't seem to exist when the schema.rb import completes, this causes a breakdown as well

notes: rails 5 api-mode

(1)

```
irb(main):005:0> Apartment::Tenant.create(f.tenant_schema_name)
   (6.2ms)  CREATE DATABASE `tenant_foo` DEFAULT CHARACTER SET `utf8`
   (5.3ms)  SELECT DATABASE() as db
   (5.3ms)  use `tenant_foo`
   (5.8ms)  DROP TABLE `access_logs` CASCADE
```

results in 

```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown table 'tenant_foo.access_logs': DROP TABLE `access_logs` CASCADE
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:46:in `execute'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:464:in `drop_table'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:280:in `create_table'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:420:in `create_table'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/migration.rb:845:in `block in method_missing'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/migration.rb:814:in `block in say_with_time'
    from /usr/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
... 9 levels...
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:217:in `import_database_schema'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:27:in `block (2 levels) in create'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:106:in `switch'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:26:in `block in create'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:23:in `create'
    from (irb):5
```

(2) 

```
irb(main):004:0> Apartment::Tenant.create(f.tenant_schema_name)
   (6.1ms)  CREATE DATABASE `tenant_foo` DEFAULT CHARACTER SET `utf8`
   (5.4ms)  SELECT DATABASE() as db
   (5.7ms)  use `tenant_foo`
   (22.1ms)  CREATE TABLE `access_logs` (`id` int AUTO_INCREMENT PRIMARY KEY, `content_id` 
>>> truncated, for brevity, successfully gets to the end of the schema.rb <<<
   (20.9ms)  CREATE  INDEX `index_things_on_uuid` USING btree ON `things` (`uuid`)
   (5.6ms)  SELECT version FROM `schema_migrations`
```

results in

```
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'tenant_foo.schema_migrations' doesn't exist: SELECT version FROM `schema_migrations`
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:46:in `execute'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:80:in `select_result'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:32:in `select_rows'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `select_values'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:1026:in `assume_migrated_upto_version'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/schema.rb:52:in `define'
... 4 levels...
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:217:in `import_database_schema'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:27:in `block (2 levels) in create'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:106:in `switch'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:26:in `block in create'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/apartment-1.2.0/lib/apartment/adapters/abstract_adapter.rb:23:in `create'
    from (irb):4
```

**Comment by Xorelock** [comment] 2016-07-28 20:18
These 2 lines of backtrace are really odd
```
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:1026:in `assume_migrated_upto_version'
    from /app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/schema.rb:52:in `define'
```

active_record/schema.rb lines 50-53:
```
      if info[:version].present?
        initialize_schema_migrations_table
        connection.assume_migrated_upto_version(info[:version], migrations_paths)
      end
```
one might assume that if line 52 (failing) has run, then the schema migrations table has been initialized...

digging deeper, one finds that SchemaMigration.table_exists?(table_name) is checked, but when you drill down to abstract_mysql_adapter in ar-5, you find that data_source_exists?(table_name) -> extract_schema_qualified_name(table_name), but since the table_name that gets passed down is "schema_migrations" rather than "tenant_foo.schema_migrations", it defaults to the connection's @config[:database], which is still the parent db. metadata lookup ensues, which finds the parent db's schema_migration table.

ways to mitigate:
1) update connection's @config[:database]
2) monkey-patch ar to qualify the table_name
3) ???

**Comment by Xorelock** [comment] 2016-07-28 22:23
ok so i was looking at abstract_adapter's connect_to_new, which does the following:
```
      def connect_to_new(tenant)
        Apartment.establish_connection multi_tenantify(tenant)
        Apartment.connection.active?   # call active? to manually check if this connection is valid
      rescue *rescuable_exceptions => exception
        Apartment::Tenant.reset if reset_on_connection_exception?
        raise_connect_error!(tenant, exception)
      end
```

however, this is overridden by mysql2_adapter:
```
      def connect_to_new(tenant)
        return reset if tenant.nil?

        Apartment.connection.execute "use `#{environmentify(tenant)}`"

      rescue ActiveRecord::StatementInvalid => exception
        Apartment::Tenant.reset
        raise_connect_error!(tenant, exception)
      end
```

as you can see here, this doesn't attempt to push the tenant's name into the connection's config

I've got a monkey patch which fixes this for me, i don't feel strongly that it's the right solution, but at the end of the day, it gets the job done.

```
require 'apartment/adapters/mysql2_adapter'

class Apartment::Adapters::Mysql2SchemaAdapter

  def connect_to_new(tenant)
    return reset if tenant.nil?

    Apartment.connection.instance_variable_get(:@config)[:database] = tenant
    Apartment.connection.execute "use `#{environmentify(tenant)}`"

  rescue ActiveRecord::StatementInvalid => exception
    Apartment::Tenant.reset
    raise_connect_error!(tenant, exception)
  end

end
```

**Comment by mikecmpbll** [comment] 2016-08-01 08:18
not sure that i understand what's going on here. where's the drop table coming from? for the mysql2 adapter `create` just calls create_database on the connection and then loads the schema and any seed data if available.

pretty sure @config is intended to be the 'default' config, when apartment is initialized, hence it's used in reset. nowhere destructively modifies @config; the multitenantify methods clone it.

**Comment by Xorelock** [comment] 2016-08-09 21:03
ok so i did this all 2 weeks ago so let me try to reiterate:

during schema_migrations table initialization, or the initialization of any table that might be specified in schema.rb, the code first needs to answer the question: "Does this table exist already?"

* If the table exists, drop the table and recreate (any application table) or do nothing (schema_migrations)
* If the table does not exists, create the table.

Now, to answer this question, it *SHOULD* be looking at the schema of the specific tenant we're dealing with. in *ACTUALITY*, the active record adapter is looking at the schema specified by config[:database]. And since the mysql2_adapter does not actually invoke any of the multitenantify (was that intentional or an oversight?), the end result is: when asking "does schema_migrations/any_table exist for tenant_foo", it answers with the result of "does schema_migrations/any_table exist for default_schema"

This explains how both errors in my original post came about.

Hopefully the way i have explained it makes sense.

**Comment by alexandre025** [comment] 2016-08-18 08:24
I'm experiencing exactly the same issue on rails5 (not api mode in my case), thanks for your explanations

**Comment by dougsq** [comment] 2016-11-07 02:21
I was going through the similar issue with separate database per tenant using mysql. 

Turns out if you set config.use_schemas = false` in the apartment.rb initializer it gets rid of the the issue where the drop table fails because of ActiveRecord trying to quote the table names with the database (tenant) name:

```ruby 
`ActiveRecord::StatementInvalid: Mysql2::Error: Unknown table 'mytenant.mytable': DROP TABLE `mytable` CASCADE`
```

Which makes sense. 

I could have saved a lot of work except that the comments in the apartment.rb have that config item under the heading the PostgreSQL only options, which is not true for the `use_schemas` option, which defaults to true and causes issues with MySql:

```ruby
#
# ==> PostgreSQL only options

# Specifies whether to use PostgreSQL schemas or create a new database per Tenant.
# The default behaviour is true.
#
config.use_schemas = false
```

So using 1.2 with no additional patches, seems to work creating a separate database per Tenant under MySql and using the Subdomain Elevator.

**Comment by BillyParadise** [comment] 2016-11-10 10:33
confirmed.  Using mysql in development on a Rails 5 project, I fixed the problem by using the above solution (config.use_schemas = false).  No production deployment yet.

**Comment by mikecmpbll** [comment] 2016-11-10 16:06
will delve in to this tonight :+1:

**Comment by dejan-stankovic** [comment] 2016-12-15 18:11
any progress on this?

**Comment by mizukami234** [comment] 2017-01-17 15:00
Hi.

I'm having trouble with the same issue.
This is my investigation:

This bug occurs because:
AR decides to drop table if it's already exists before creating table with :force option,
where AR searches existing table from database specified in `@config[:database]` (public tenant!).
Therefore, any `USE databasename` statement before `create_table` does not change the database to search table from.

But I'm not sure that changing `@config[:database]` from Apartment is the proper way to fix this because some other gems might not want this option to be changed.

Contrary in postgres, AR dynamically chooses schemas via PG's `current_schemas` syntax.

So it can be said that there is no reason why AR's mysql adapter should decides database name statically from `@config[:database]`.

Finally, I decided to patch AR's mysql adapter to fix this.

Here is the patch:

```rb
module ActiveRecord
  module ConnectionAdapters
    class AbstractMysqlAdapter < AbstractAdapter
      def extract_schema_qualified_name(string)
        schema, name = string.to_s.scan(/[^`.\s]+|`[^`]*`/)
        unless name
          name = schema
          schema = current_database # select current database dynamically
        end
        [schema, name]
      end
    end
  end
end
```

I've not investigated how this patch can affect AR's behavior yet.

Now I want some reviews whether this approach is good or not.
I could PR to AR if need.

I also tried `use_schemas = false` and it seems the good way, but unfortunately it disables database_cleaner gem's transaction strategy. That was not practical for me ;)

**Comment by mikecmpbll** [comment] 2017-01-18 12:04
@mizukami234 ❤️ thanks so much for looking in to this

i was uneasy with the proposed changes here for the same reason as you, and for the fact that the config is meant to represent the default so not be modified, but i hadn't gotten around to investigating in as much detail as you.

my analysis is from looking at the AR code is that the behaviour has changed because they switched from using `SHOW TABLES LIKE`, which without a database name provided defaults to the current database, to looking at `information_schema.tables`. the reason for the change was `SHOW TABLES LIKE` has wildcard behaviour which was producing spurious results for tables with `_` in the name, for example.

i don't know what rails would want to do about this, but i definitely think it's worth creating an issue about because using `@config[:database]` in the adapter doesn't feel good to me.

**Comment by mikecmpbll** [comment] 2017-06-29 08:30
issue addressed in rails, not sure exactly which versions it got backported to but 5.1 certainly has it.

**Closed by mikecmpbll** 2017-06-29 08:30 UTC
