### ISSUE TITLE
Problems when configure seed_after_create = true

### ISSUE THREAD

**Issue by marcosgugs** [influitive/apartment#204] opened 2015-01-22 13:25 UTC
Hi guys, I have a problem in Apartment when configured seed_after_create = true.
The idea is to run seed after create an Tenant. 
In the first time, Apartment run seed correctly after create a new Tenant. But, after this, when run again to create a new Tenant, Apartment don't run the seed. 
I need restart server and create again the Tenant to the Apartment run seed correctly, but, when I create other Tenant, Apartment don't run seed again.

Anybody have this problem?

Sorry for my bad english!

**Comment by bradrobertson** [comment] 2015-01-22 15:39
Seems odd. We do the exact same thing and we create tenants all the time.

**Comment by raulperezalejo** [comment] 2015-01-23 20:24
YES i have exactly the same problem, in my debugging i have reach up to "load_or_abort" method in the abstract_adapter.rd, where i reach two time, the first one is in the method to load the schema 'import_database_schema' and the second time in the 'seed_data' method. 
As far as i have seen the method simply don't 'load' the '(file)'. 
as similar as my collegue i need to restart the server. 
ruby 212
rails 416

regards

**Comment by raulperezalejo** [comment] 2015-01-23 21:44
I have found that maybe is not a problem of Apartment, because i have tryed with this code to have a similar functionality as 'seed_after_create' 

        Apartment::Tenant.switch(@account.subdomain)
        Rake::Task['db:seed'].invoke
        Rake::Task['db:seed'].reenable
        Rake::Task['spree_sample:load'].invoke
        Rake::Task['spree_sample:load'].reenable
        Apartment::Tenant.switch('public')

and the same odd think happends, even i get a 

'loading ruby {name of the .rb}' 

it only works the first time, the second, the table is empty and i have to restart the server, so maybe is not a problem of Apartment. 

I am using rake 10.4.2

hope it helps

**Comment by raulperezalejo** [comment] 2015-02-03 17:39
this is not an Apartment problem, you can close this issue. 
The problem is with Spree, wich load the seeds using "require" insted of "load"

you can close this issue. 

Regards

**Closed** 2015-02-03 18:02 UTC
